MODEL: "ConvNextBase"
DEVICE: "cuda"
EPOCHS: 30
NUM_CLASSES: 512
BATCH_SIZE: 256
PRETRAIN: True
LR: 1e-4
LOSS: LabelSmooth_CE
STOCH_DEPTH_PROB: None
MIXUP: False
LR_STEP_SIZE: 15
NUM_WORKERS: 4
DATA_PATH: "./data/test_aug_noise_data"
TRAIN_SIZE: 0.8
SEED: 42

HIER_MODEL:
  COARSE_MODEL: "ConvNextBase"
  FINE_MODEL: "ConvNextBase"
  COARSE_MODEL_EPOCHS: 5
  FINE_MODEL_EPOCHS: 5
  COARSE_OVD: True
  FINE_OVD: True
  COARSE_DATA_PATH: "./data/hierarchical_data/coarse_data"
  FINE_DATA_PATH: "./data/hierarchical_data/fine_data"
