MODEL: "ResNet50"
DEVICE: "cuda"
EPOCHS: 30
BATCH_SIZE: 256
LR: 1e-4
LOSS: LabelSmooth_CE
NUM_WORKERS: 4
DATA_PATH: "./data/aug_noise_data"
TRAIN_SIZE: 0.8
SEED: 42
RUNS_FOLDER: "./trained_weights/ResNet34_20250320_043832"
