MODEL: "ResNet50" # src/models/__init__.py list all available models architecure
DEVICE: "cuda" # mps # cpu
EPOCHS: 150
NUM_CLASSES: 100 # if --model_type ovd_classification, change NUM_CLASSES to 512 (embedding dimension)
BATCH_SIZE: 256
PRETRAIN: False # if the model without pretrained weights, setting this to True will be the same as setting to False
LR: 1e-2
# available Loss (criterion): 
# 1. CE (Cross Entropy Loss) 2. LabelSmooth_CE (CE with LabelSmooth) 3. FL (FocalLoss)
LOSS: LabelSmooth_CE 
STOCH_DEPTH_PROB: None # Only for ConvNext 
NUM_WORKERS: 4
DATA_PATH: "./data/aug_noise_data_v2_5" # path to training data
TRAIN_SIZE: 0.8 # train/val data split proportion
SEED: 42

TRANSFORM: # training transform 
  # CUTMIX: True
  MIXUP: False 
  AUTOAUG: True # Autoaug Cifar10
  ERASE_PROB: 0.2

HIER_MODEL: # if --model_type hierarchical_classification
  COARSE_MODEL: "ConvNextBase"
  FINE_MODEL: "ConvNextBase"
  COARSE_MODEL_EPOCHS: 5
  FINE_MODEL_EPOCHS: 5
  COARSE_OVD: True
  FINE_OVD: True
  COARSE_DATA_PATH: "./data/hierarchical_data/coarse_data"
  FINE_DATA_PATH: "./data/hierarchical_data/fine_data"
