MODEL: "ResNet50"
DEVICE: "cuda"
EPOCHS: 150
NUM_CLASSES: 100
BATCH_SIZE: 256
PRETRAIN: False
LR: 1e-2
LOSS: LabelSmooth_CE
STOCH_DEPTH_PROB: None
LR_STEP_SIZE: 15
NUM_WORKERS: 4
DATA_PATH: "./data/aug_noise_data_v2_5"
TRAIN_SIZE: 0.8
SEED: 42

TRANSFORM:
  # CUTMIX: True
  MIXUP: False
  AUTOAUG: True
  ERASE_PROB: 0.2

HIER_MODEL:
  COARSE_MODEL: "ConvNextBase"
  FINE_MODEL: "ConvNextBase"
  COARSE_MODEL_EPOCHS: 5
  FINE_MODEL_EPOCHS: 5
  COARSE_OVD: True
  FINE_OVD: True
  COARSE_DATA_PATH: "./data/hierarchical_data/coarse_data"
  FINE_DATA_PATH: "./data/hierarchical_data/fine_data"
