MODEL: "ConvNextTiny"
DEVICE: "mps"
EPOCHS: 30
NUM_CLASSES: 100
BATCH_SIZE: 256
PRETRAIN: False
LR: 1e-4
LOSS: FC
STOCH_DEPTH_PROB: None
MIXUP: True
LR_STEP_SIZE: 15
NUM_WORKERS: 4
DATA_PATH: "./data/test_aug_noise_data"
TRAIN_SIZE: 0.8
SEED: 42
