MODEL: "SimpleCNN"
DEVICE: "mps"
EPOCHS: 30
BATCH_SIZE: 512
LR: 1e-4
LOSS: LabelSmooth_CE
NUM_WORKERS: 4
DATA_PATH: "./data/cifar100_data"
TRAIN_SIZE: 0.8
SEED: 42
RUNS_FOLDER: "./trained_weights/SimpleCNN_20250319_190807"